basic game collection
$Id: mulk/basic basgames.mm 1442 2025-06-12 Thu 10:05:28 kt $

.caption DESCRIPTION
This is 70-80s basic game collection.

*Basic computer games micro computer edition
.summary aceyducy
.summary amazing
.summary animal
.summary awari
.summary bagels
.summary bannerb
.summary basketbl
.summary batnum
.summary battle
.summary blackjck
.summary bmbrdmnt
.summary bombsawy
.summary bowling
.summary boxing
.summary bug
.summary bullfght
.summary bullseye
.summary bunny
.summary buzzword
.summary calendar
.summary change
.summary checkers
.summary chemist
.summary chief
.summary chomp
.summary civilwar
.summary combat
.summary craps
.summary cube
.summary dpthchrg
.summary diamond
.summary diceb
.summary digits
.summary evenwins
.summary evenwns2
.summary flipflop
.summary football
.summary footbll2
.summary furtradr
.summary golf
.summary guess
.summary gunner
.summary hamurabi
.summary hangman
.summary hellob
.summary hexapawn
.summary hilo
.summary hiq
.summary hockey
.summary horserac
.summary hurkle
.summary kinema
.summary king
.summary letter
.summary lifeb
.summary life2
.summary literatr
.summary love
.summary lunar
.summary lem
.summary rocket
.summary mastrmnd
.summary mathdice
.summary mugwump
.summary name
.summary nicoma
.summary nim
.summary number
.summary onecheck
.summary orbit
.summary pizza
.summary poetry
.summary poker
.summary queen
.summary reverseb
.summary rocksp
.summary roulette
.summary rusrou
.summary salvo
.summary sinewave
.summary slalom
.summary slots
.summary splat
.summary stars
.summary stock
.summary sstrek
.summary synonym
.summary target
.summary 3dplot
.summary qubic
.summary ttt
.summary ttt2
.summary towers
.summary train
.summary trap
.summary 23match
.summary war
.summary weekday
.summary word

*More basic computer games.
.summary artllry3
.summary baccarat
.summary biblequz
.summary big6
.summary binary
.summary blackbox
.summary bobstons
.summary bocce
.summary boga2
.summary bombrun
.summary bridgeit
.summary camel
.summary chase
.summary chucklck
.summary clsencnt
.summary column
.summary cncntrtn
.summary condot
.summary convoy
.summary corral
.summary countdwn
.summary cup
.summary dealerx5
.summary deepspac
.summary defuse
.summary dodgem
.summary doors
.summary drag
.summary drz
.summary eliza
.summary father
.summary flip
.summary fourinrw
.summary geowar
.summary grnprx
.summary guessit
.summary icbm
.summary inkblot
.summary joust
.summary jmpngbll
.summary keno
.summary lgame
.summary lfexpctn
.summary lissajub
.summary magicsqr
.summary mnetngrb
.summary maneuvrs
.summary mstrmnd2
.summary mstrbgls
.summary matpuzzl
.summary mazeb
.summary millionr
.summary minotaur
.summary motrcycl
.summary nomad
.summary notone
.summary obstacle
.summary octrix
.summary pasart
.summary pasart2
.summary pinball
.summary rabbtchs
.summary roadrace
.summary rotate
.summary safe
.summary scales
.summary schmoo
.summary seabattl
.summary seawar
.summary shoot
.summary smash
.summary strike9
.summary tennis
.summary tickertp
.summary tvplot
.summary twonky
.summary twototen
.summary ufo
.summary underovr
.summary vangam
.summary warfish
.summary wumpus
.summary wumpus2

*Basic computer adventures.
.summary marco
.summary westho
.summary autorace
.summary orient
.summary earhart
.summary tour
.summary appalchn
.summary subway
.summary hongkong
.summary neptune

*misc
.summary oregntrl
.summary lemonade
